[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["graphqlcatalogapi"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "graphqlcatalogapi"
  org = "lashanaah"
  version = "1.0.1"

